# connectors/intercom/constants.py

from __future__ import annotations

BASE_URL = "https://api.intercom.io"
CONNECTOR_NAME = "intercom"

# Conservative defaults (Intercom endpoints vary by model/tenant)
PAGE_SIZE_CONTACTS_LIST = 50
PAGE_SIZE_CONVERSATIONS_LIST = 50

# Search endpoints use pagination.per_page (often up to 150, but contacts search is commonly smaller)
PAGE_SIZE_SEARCH_DEFAULT = 150
PAGE_SIZE_SEARCH_CONTACTS_DEFAULT = 50

# State keys (per-stream cursors for correctness)
STATE_CURSOR_CONTACTS = "intercom_contacts_last_updated_at"
STATE_CURSOR_COMPANIES = "intercom_companies_last_updated_at"
STATE_CURSOR_CONVERSATIONS = "intercom_conversations_last_updated_at"
STATE_CURSOR_TICKETS = "intercom_tickets_last_updated_at"
STATE_CURSOR_PARTS = "intercom_parts_last_updated_at"

# Env toggles
ENV_SYNC_CONTACTS = "INTERCOM_SYNC_CONTACTS"
ENV_SYNC_COMPANIES = "INTERCOM_SYNC_COMPANIES"
ENV_SYNC_CONVERSATIONS = "INTERCOM_SYNC_CONVERSATIONS"
ENV_SYNC_PARTS = "INTERCOM_SYNC_PARTS"
ENV_SYNC_TICKETS = "INTERCOM_SYNC_TICKETS"

ENV_FORCE_FULL = "INTERCOM_FORCE_FULL"
ENV_START_AT_EPOCH = "INTERCOM_START_AT_EPOCH"

ENV_HYDRATE_WORKERS = "INTERCOM_HYDRATE_WORKERS"
ENV_HYDRATE_MAX_IN_FLIGHT = "INTERCOM_HYDRATE_MAX_IN_FLIGHT"

ENV_RATE_LIMIT_REMAINING_FLOOR = "INTERCOM_RATE_LIMIT_REMAINING_FLOOR"
ENV_RATE_LIMIT_MAX_SLEEP = "INTERCOM_RATE_LIMIT_MAX_SLEEP"

ENV_EXPAND_CUSTOM_ATTRIBUTES = "INTERCOM_EXPAND_CUSTOM_ATTRIBUTES"
ENV_MAX_CUSTOM_ATTR_COLUMNS = "INTERCOM_MAX_CUSTOM_ATTR_COLUMNS"
ENV_FLATTEN_MAX_DEPTH = "INTERCOM_FLATTEN_MAX_DEPTH"

ENV_EVENT_LOG_PATH = "CONNECTOR_UI_EVENT_LOG"
ENV_RUN_ID = "RUN_ID"

# Companies “pull everything” option:
ENV_COMPANIES_USE_SCROLL = "INTERCOM_COMPANIES_USE_SCROLL"  # default true
